# Generated by Django 4.2.25 on 2025-10-24 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_past_options_past_created_at_past_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
